=== AndreuSanchezGuerrero/ASIX-DAW/M04 - Marques/UF1/A04_01e_NMC/classe2/classe2.dtd
<!ELEMENT classe (tutor, alumne+)>
<!ELEMENT tutor (NIF, nom, cognom+, telefon*, email*)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT alumne (NIF, nom, cognom+, telefon*, email*)>

=== AndreuSanchezGuerrero/ASIX-DAW/Marques/UF1/A04_01e_NMC/classe2/classe2.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE classe SYSTEM "classe2.dtd">
<classe>
    <tutor>
        <NIF>376255174W</NIF>
        <nom>Barry</nom>
        <cognom>Helga</cognom>
        <cognom>Kenneth</cognom>
        <telefon>668532657</telefon>
        <telefon>628836569</telefon>
        <email>B.Helga@gmail.com</email>
    </tutor>
    <alumne>
        <NIF>449252125Y</NIF>
        <nom>Hawly</nom>
        <cognom>Leigh</cognom>
        <telefon>613590147</telefon>
        <telefon>641488454</telefon>
        <telefon>643373073</telefon>
    </alumne>
    <alumne>
        <NIF>427555454R</NIF>
        <nom>Kenneth</nom>
        <cognom>Baethan</cognom>
        <telefon>644626170</telefon>
        <telefon>692684516</telefon>
        <email>K.Baethan@sapalomera.cat</email>
        <email>K.Baethan@gmail.com</email>
    </alumne>
    <alumne>
        <NIF>622984754W</NIF>
        <nom>Lamar</nom>
        <cognom>Kedric</cognom>
        <cognom>Brandon</cognom>
        <cognom>Bayard</cognom>
        <telefon>644271545</telefon>
        <email>L.Kedric@gmail.com</email>
    </alumne>
    <alumne>
        <NIF>809779179P</NIF>
        <nom>Helma</nom>
        <cognom>Harmony</cognom>
        <telefon>629418633</telefon>
    </alumne>
    <alumne>
        <NIF>170393389L</NIF>
        <nom>Haslett</nom>
        <cognom>Ingrid</cognom>
        <cognom>Bingham</cognom>
    </alumne>
    <alumne>
        <NIF>776915277O</NIF>
        <nom>Kacia</nom>
        <cognom>Hartman</cognom>
        <cognom>Helga</cognom>
        <cognom>Harriet</cognom>
        <telefon>675190747</telefon>
        <telefon>688463503</telefon>
        <email>K.Hartman@gmail.com</email>
    </alumne>
    <alumne>
        <NIF>152882536V</NIF>
        <nom>Harris</nom>
        <cognom>Konrad</cognom>
        <cognom>Iris</cognom>
        <email>H.Konrad@sapalomera.cat</email>
        <email>H.Konrad@sapalomera.cat</email>
    </alumne>
    <alumne>
        <NIF>620529519N</NIF>
        <nom>Lafayette</nom>
        <cognom>Ian</cognom>
        <cognom>Anabel</cognom>
        <telefon>682328682</telefon>
    </alumne>
    <alumne>
        <NIF>243794308V</NIF>
        <nom>Haven</nom>
        <cognom>Beacher</cognom>
        <telefon>632353444</telefon>
    </alumne>
    <alumne>
        <NIF>522971556I</NIF>
        <nom>Baxter</nom>
        <cognom>Beau</cognom>
        <cognom>Hawly</cognom>
        <telefon>693941636</telefon>
        <telefon>662447092</telefon>
        <telefon>684292126</telefon>
    </alumne>
    <alumne>
        <NIF>338318805U</NIF>
        <nom>Bertin</nom>
        <cognom>Hearne</cognom>
        <telefon>698032264</telefon>
        <telefon>628837293</telefon>
    </alumne>
    <alumne>
        <NIF>748574698S</NIF>
        <nom>Bertin</nom>
        <cognom>Kyle</cognom>
        <telefon>638803786</telefon>
    </alumne>
    <alumne>
        <NIF>911877117E</NIF>
        <nom>Kalista</nom>
        <cognom>Autumn</cognom>
        <cognom>Hardy</cognom>
        <telefon>620805629</telefon>
        <telefon>673053601</telefon>
        <email>K.Autumn@gmail.com</email>
        <email>K.Autumn@gmail.com</email>
    </alumne>
    <alumne>
        <NIF>129026639E</NIF>
        <nom>Kimball</nom>
        <cognom>Konrad</cognom>
    </alumne>
</classe>
