=== AndreuSanchezGuerrero/ASIX-DAW/Marques/UF1/Examen/Apartat4/4_1/apartat_4_1_enunciat.dtd
<!ELEMENT socis (soci+)>
<!ELEMENT soci (((num, data) | clau)?, nom, cognom, cognom?, (datanaixement | edat), telefon+)>
<!ELEMENT num (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT clau (#PCDATA)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT cognom (#PCDATA)>
<!ELEMENT datanaixement (#PCDATA)>
<!ELEMENT edat (#PCDATA)>
<!ELEMENT telefon (#PCDATA)>

=== AndreuSanchezGuerrero/ASIX-DAW/M04 - Marques/UF1/Examen/Apartat4/4_1/apartat_4_1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE socis SYSTEM "apartat_4_1_enunciat.dtd">
<socis>
    <soci>
        <clau>KU0A4BES</clau>
        <nom>Katherine</nom>
        <cognom>Beacan</cognom>
        <cognom>Laurent</cognom>
        <datanaixement>13/12/2002</datanaixement>
        <telefon>650843549</telefon>
        <telefon>666508450</telefon>
        <telefon>697095716</telefon>
    </soci>
    <soci>
        <clau>53BGDMRD</clau>
        <nom>Ken</nom>
        <cognom>Baen</cognom>
        <edat>48</edat>
        <telefon>618813978</telefon>
        <telefon>638633214</telefon>
    </soci>
    <soci>
        <clau>5P3NFQJC</clau>
        <nom>Kenneth</nom>
        <cognom>Barton</cognom>
        <cognom>Hannah</cognom>
        <datanaixement>27/8/2003</datanaixement>
        <telefon>612156752</telefon>
    </soci>
    <soci>
        <clau>MAHW6SCT</clau>
        <nom>Kerwin</nom>
        <cognom>Booker</cognom>
        <cognom>Kaitlyn</cognom>
        <edat>39</edat>
        <telefon>614915113</telefon>
        <telefon>696857134</telefon>
        <telefon>655215114</telefon>
    </soci>
    <soci>
        <nom>Lehman</nom>
        <cognom>Lear</cognom>
        <cognom>Lars</cognom>
        <edat>37</edat>
        <telefon>623873152</telefon>
    </soci>
    <soci>
        <clau>807_2020-01-19</clau>
        <nom>Huela</nom>
        <cognom>Leigh</cognom>
        <datanaixement>5/2/2001</datanaixement>
        <telefon>699990642</telefon>
        <telefon>647943920</telefon>
        <telefon>679857466</telefon>
    </soci>
    <soci>
        <clau>546_2020-01-19</clau>
        <nom>Autumn</nom>
        <cognom>Hawly</cognom>
        <cognom>Baldwin</cognom>
        <datanaixement>10/3/1998</datanaixement>
        <telefon>660009242</telefon>
        <telefon>638335826</telefon>
        <telefon>651756756</telefon>
    </soci>
    <soci>
        <nom>Hearne</nom>
        <cognom>Harbin</cognom>
        <cognom>Konrad</cognom>
        <datanaixement>15/11/2003</datanaixement>
        <telefon>625572256</telefon>
        <telefon>680384849</telefon>
    </soci>
    <soci>
        <clau>XA4KOW17</clau>
        <nom>Ignatius</nom>
        <cognom>Landis</cognom>
        <cognom>Helga</cognom>
        <edat>31</edat>
        <telefon>643155087</telefon>
        <telefon>656681348</telefon>
    </soci>
    <soci>
        <clau>R5SELAJA</clau>
        <nom>Harland</nom>
        <cognom>Blaine</cognom>
        <cognom>Blaine</cognom>
        <datanaixement>16/9/2000</datanaixement>
        <telefon>618009228</telefon>
    </soci>
    <soci>
        <clau>253_2020-01-19</clau>
        <nom>Hardy</nom>
        <cognom>Blake</cognom>
        <cognom>Leigh</cognom>
        <datanaixement>16/4/2000</datanaixement>
        <telefon>653317629</telefon>
    </soci>
    <soci>
        <clau>8ULTQGQR</clau>
        <nom>Barrington</nom>
        <cognom>Hannah</cognom>
        <datanaixement>27/6/2002</datanaixement>
        <telefon>631278374</telefon>
    </soci>
    <soci>
        <clau>6SZEVEHZ</clau>
        <nom>Hilary</nom>
        <cognom>Benen</cognom>
        <cognom>Holda</cognom>
        <edat>22</edat>
        <telefon>690630552</telefon>
    </soci>
    <soci>
        <clau>461_2020-01-19</clau>
        <nom>Arielle</nom>
        <cognom>Baldwin</cognom>
        <cognom>Kyle</cognom>
        <edat>41</edat>
        <telefon>682691400</telefon>
    </soci>
    <soci>
        <clau>RJOMIO3K</clau>
        <nom>Hendrix</nom>
        <cognom>Landis</cognom>
        <edat>27</edat>
        <telefon>651130719</telefon>
        <telefon>638125361</telefon>
    </soci>
    <soci>
        <clau>ALFKA1ZQ</clau>
        <nom>Barrington</nom>
        <cognom>Benjamin</cognom>
        <edat>25</edat>
        <telefon>639858798</telefon>
        <telefon>687984029</telefon>
        <telefon>682967116</telefon>
        <telefon>684157120</telefon>
    </soci>
    <soci>
        <clau>441_2020-01-19</clau>
        <nom>Basil</nom>
        <cognom>Bradley</cognom>
        <cognom>Haven</cognom>
        <edat>44</edat>
        <telefon>670001320</telefon>
        <telefon>638111134</telefon>
        <telefon>680030772</telefon>
    </soci>
    <soci>
        <nom>Autumn</nom>
        <cognom>Benen</cognom>
        <datanaixement>18/6/1999</datanaixement>
        <telefon>662881148</telefon>
        <telefon>636597452</telefon>
        <telefon>684386568</telefon>
    </soci>
    <soci>
        <clau>GHW37QFO</clau>
        <nom>Lancelot</nom>
        <cognom>Lawley</cognom>
        <cognom>Harcourt</cognom>
        <edat>38</edat>
        <telefon>663988084</telefon>
    </soci>
    <soci>
        <clau>818_2020-01-19</clau>
        <nom>Lambart</nom>
        <cognom>Harris</cognom>
        <cognom>Arielle</cognom>
        <edat>23</edat>
        <telefon>694006756</telefon>
        <telefon>665314418</telefon>
        <telefon>691465190</telefon>
        <telefon>675794569</telefon>
    </soci>
    <soci>
        <clau>J0MMIUNK</clau>
        <nom>Iona</nom>
        <cognom>Barton</cognom>
        <edat>19</edat>
        <telefon>636611296</telefon>
        <telefon>694933243</telefon>
    </soci>
    <soci>
        <clau>V1ZOXVB3</clau>
        <nom>Iris</nom>
        <cognom>Layton</cognom>
        <edat>43</edat>
        <telefon>696158948</telefon>
        <telefon>613627742</telefon>
        <telefon>685781779</telefon>
    </soci>
    <soci>
        <clau>HJPC6O17</clau>
        <nom>Helma</nom>
        <cognom>Lamar</cognom>
        <cognom>Iris</cognom>
        <datanaixement>5/8/1997</datanaixement>
        <telefon>679727534</telefon>
        <telefon>665986997</telefon>
        <telefon>670139755</telefon>
        <telefon>623973316</telefon>
    </soci>
    <soci>
        <clau>578_2020-01-19</clau>
        <nom>Ariana</nom>
        <cognom>Brandon</cognom>
        <edat>31</edat>
        <telefon>622327957</telefon>
        <telefon>675163717</telefon>
        <telefon>628608704</telefon>
    </soci>
    <soci>
        <clau>F3DXF0UR</clau>
        <nom>Kedric</nom>
        <cognom>Brock</cognom>
        <datanaixement>8/12/2001</datanaixement>
        <telefon>669423083</telefon>
        <telefon>694321652</telefon>
        <telefon>636204543</telefon>
        <telefon>688321209</telefon>
    </soci>
    <soci>
        <clau>T9JMGPTL</clau>
        <nom>Leigh</nom>
        <cognom>Hilary</cognom>
        <edat>18</edat>
        <telefon>652906588</telefon>
    </soci>
    <soci>
        <clau>475_2020-01-19</clau>
        <nom>Keith</nom>
        <cognom>Banning</cognom>
        <cognom>Kelly</cognom>
        <datanaixement>6/7/1998</datanaixement>
        <telefon>681728849</telefon>
        <telefon>642033590</telefon>
        <telefon>672337234</telefon>
    </soci>
    <soci>
        <nom>Lance</nom>
        <cognom>Hartwood</cognom>
        <datanaixement>20/4/1998</datanaixement>
        <telefon>675687009</telefon>
        <telefon>699474692</telefon>
        <telefon>635770231</telefon>
        <telefon>658317363</telefon>
    </soci>
    <soci>
        <nom>Hendrix</nom>
        <cognom>Blaine</cognom>
        <cognom>Lamont</cognom>
        <datanaixement>10/1/1999</datanaixement>
        <telefon>628925641</telefon>
        <telefon>632536392</telefon>
    </soci>
    <soci>
        <nom>Kenneth</nom>
        <cognom>Lasalle</cognom>
        <cognom>Idelle</cognom>
        <edat>30</edat>
        <telefon>686503576</telefon>
        <telefon>694800372</telefon>
        <telefon>669715592</telefon>
    </soci>
    <soci>
        <clau>838_2020-01-19</clau>
        <nom>Iona</nom>
        <cognom>Landis</cognom>
        <edat>41</edat>
        <telefon>612800801</telefon>
        <telefon>664071876</telefon>
        <telefon>683043321</telefon>
        <telefon>681392660</telefon>
    </soci>
    <soci>
        <clau>G8OW8RP4</clau>
        <nom>Brock</nom>
        <cognom>Basil</cognom>
        <cognom>Heloise</cognom>
        <datanaixement>24/6/2000</datanaixement>
        <telefon>645723974</telefon>
        <telefon>654083799</telefon>
        <telefon>676952002</telefon>
    </soci>
    <soci>
        <nom>Ariana</nom>
        <cognom>Baird</cognom>
        <cognom>Lance</cognom>
        <edat>26</edat>
        <telefon>648912107</telefon>
        <telefon>662795533</telefon>
    </soci>
    <soci>
        <clau>504_2020-01-19</clau>
        <nom>Kolby</nom>
        <cognom>Lars</cognom>
        <edat>23</edat>
        <telefon>663997232</telefon>
        <telefon>694761179</telefon>
        <telefon>667101122</telefon>
        <telefon>634371360</telefon>
    </soci>
    <soci>
        <nom>Baldemar</nom>
        <cognom>Konrad</cognom>
        <cognom>Lawley</cognom>
        <datanaixement>13/4/2001</datanaixement>
        <telefon>628685430</telefon>
        <telefon>668718613</telefon>
    </soci>
    <soci>
        <clau>277_2020-01-19</clau>
        <nom>Leal</nom>
        <cognom>Brock</cognom>
        <cognom>Baen</cognom>
        <edat>38</edat>
        <telefon>643400007</telefon>
        <telefon>666657062</telefon>
    </soci>
    <soci>
        <clau>DYJLOEIG</clau>
        <nom>Barrington</nom>
        <cognom>Lawley</cognom>
        <edat>47</edat>
        <telefon>698414661</telefon>
    </soci>
    <soci>
        <clau>E7SXPHVX</clau>
        <nom>Lancelot</nom>
        <cognom>Harcourt</cognom>
        <edat>21</edat>
        <telefon>686540764</telefon>
        <telefon>692805295</telefon>
        <telefon>683030692</telefon>
    </soci>
    <soci>
        <nom>Harmon</nom>
        <cognom>Kerwin</cognom>
        <cognom>Benoit</cognom>
        <datanaixement>5/10/2003</datanaixement>
        <telefon>666776511</telefon>
        <telefon>671408439</telefon>
        <telefon>641140093</telefon>
        <telefon>664597505</telefon>
    </soci>
    <soci>
        <clau>648_2020-01-19</clau>
        <nom>Arielle</nom>
        <cognom>Harcourt</cognom>
